import { Nunito } from 'next/font/google'
import './globals.css'
import ClientOnly from './components/ClientOnly'
import Navbar from './components/navbar/Navbar'
import LoginModal from './components/modals/LoginModal'
import RegisterModal from './components/modals/RegisterModal'
import ToasterProvider from './providers/ToasterProvider'
import getCurrentUser from './actions/getCurrentUser'
import Socket from './components/Socket'
import Footer from './components/footer/Footer'

const font = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'PA-HEALOT',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <Socket currentUser={currentUser} />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        <div className=' pt-27'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
